import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Header from "@/components/shared/Header";
import MainSidebar from "@/components/shared/MainSidebar";
import { Breadcrumbs } from "@/components/shared/Breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Хранилище",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className="flex h-screen w-full">
              <MainSidebar />
              <div className="flex-1 flex flex-col overflow-hidden">
                <Header />
                <Breadcrumbs />
                <main className="flex-1 overflow-auto">{children}</main>
              </div>
            </div>
            <SidebarTrigger className="fixed top-4 left-4 z-50" />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
