import { Discipline } from "@/types/presentations.type"; // Предполагаемый путь к типам

export const disciplines: Discipline[] = [
  {
    id: 1,
    title: "Математический анализ",
    lecturer: "Иванов П.С.",
    rating: 4.7,
    documents: {
      abstract: "",
      cheatSheet: "",
      presentations: [
        {
          id: 1,
          title: "Введение в анализ",
          description: "Основные понятия математического анализа",
          authorId: 101,
          subjectId: 201,
          groupId: 301,
          uploadDate: new Date("2023-09-10"),
          lastModified: new Date("2023-09-15"),
          fileName: "math_analysis_intro.pdf",
          fileType: "application/pdf",
        },
        {
          id: 2,
          title: "Пределы функций",
          description: "Теория пределов с примерами",
          authorId: 101,
          subjectId: 201,
          groupId: 301,
          uploadDate: new Date("2023-09-20"),
          lastModified: new Date("2023-09-25"),
          fileName: "function_limits.pptx",
          fileType: "application/vnd.ms-powerpoint",
        },
      ],
    },
  },
  {
    id: 2,
    title: "Программирование на C++",
    lecturer: "Петрова А.В.",
    rating: 4.9,
    documents: {
      abstract: "",
      cheatSheet: "",
      presentations: [
        {
          id: 3,
          title: "Основы C++",
          description: "Синтаксис и базовые конструкции языка",
          authorId: 102,
          subjectId: 202,
          groupId: 302,
          uploadDate: new Date("2023-10-05"),
          lastModified: new Date("2023-10-10"),
          fileName: "cpp_basics.pdf",
          fileType: "application/pdf",
        },
        {
          id: 4,
          title: "ООП в C++",
          description: "Принципы объектно-ориентированного программирования",
          authorId: 102,
          subjectId: 202,
          groupId: 302,
          uploadDate: new Date("2023-10-15"),
          lastModified: new Date("2023-10-20"),
          fileName: "cpp_oop.pptx",
          fileType: "application/vnd.ms-powerpoint",
        },
        {
          id: 5,
          title: "STL библиотека",
          description: "Стандартная библиотека шаблонов",
          authorId: 102,
          subjectId: 202,
          groupId: 302,
          uploadDate: new Date("2023-10-25"),
          lastModified: new Date("2023-10-30"),
          fileName: "cpp_stl.pdf",
          fileType: "application/pdf",
        },
      ],
    },
  },
  {
    id: 3,
    title: "История искусств",
    lecturer: "Сидоров М.К.",
    rating: 4.5,
    documents: {
      abstract: "",
      cheatSheet: "",
      presentations: [
        {
          id: 6,
          title: "Искусство Возрождения",
          description: "Шедевры эпохи Ренессанса",
          authorId: 103,
          subjectId: 203,
          groupId: 303,
          uploadDate: new Date("2023-11-05"),
          lastModified: new Date("2023-11-10"),
          fileName: "renaissance_art.pdf",
          fileType: "application/pdf",
        },
      ],
    },
  },
  {
    id: 4,
    title: "Физика",
    lecturer: "Кузнецова Е.Л.",
    rating: 4.6,
    documents: {
      abstract: "",
      cheatSheet: "",
      presentations: [
        {
          id: 7,
          title: "Механика",
          description: "Основы классической механики",
          authorId: 104,
          subjectId: 204,
          groupId: 304,
          uploadDate: new Date("2023-11-15"),
          lastModified: new Date("2023-11-20"),
          fileName: "physics_mechanics.pptx",
          fileType: "application/vnd.ms-powerpoint",
        },
        {
          id: 8,
          title: "Термодинамика",
          description: "Законы термодинамики",
          authorId: 104,
          subjectId: 204,
          groupId: 304,
          uploadDate: new Date("2023-11-25"),
          lastModified: new Date("2023-11-30"),
          fileName: "physics_thermodynamics.pdf",
          fileType: "application/pdf",
        },
      ],
    },
  },
  {
    id: 5,
    title: "Английский язык",
    lecturer: "Смирнова О.И.",
    rating: 4.8,
    documents: {
      abstract: "",
      cheatSheet: "",
      presentations: [
        {
          id: 9,
          title: "Деловая переписка",
          description: "Фразы и шаблоны для делового общения",
          authorId: 105,
          subjectId: 205,
          groupId: 305,
          uploadDate: new Date("2023-12-05"),
          lastModified: new Date("2023-12-10"),
          fileName: "english_business.pdf",
          fileType: "application/pdf",
        },
        {
          id: 10,
          title: "Грамматика: времена",
          description: "Все времена английского глагола",
          authorId: 105,
          subjectId: 205,
          groupId: 305,
          uploadDate: new Date("2023-12-15"),
          lastModified: new Date("2023-12-20"),
          fileName: "english_tenses.pptx",
          fileType: "application/vnd.ms-powerpoint",
        },
      ],
    },
  },
];
